Normalize configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #----------------------------------------------------------------------------
-#  configure script for vs_it
+#  configure script for VapourSynth_IT
 #----------------------------------------------------------------------------
 
 ## This script was modified based on d2vsource/configure.
@@ -16,7 +16,8 @@ options:
   --install=PATH           set dir for install library
                            [/usr/local/lib/vapoursynth]
 
-  --clang, --gcc           compile by g++ or clang++ [clang]
+  --cxx=CXX                use a defined compiler for compilation and linking
+                           [g++]
   --target-os=OS           build programs to run on OS [auto]
   --cross-prefix=PREFIX    use PREFIX for compilation tools
   --sysroot=SYSROOT        root of cross-build tree
@@ -59,8 +60,8 @@ cc_check()
     fi
     echo "int main(void){$4 return 0;}" >> config.log
     echo "int main(void){$4 return 0;}" >> conftest.cpp
-    echo $CXX conftest.cpp -Werror -o conftest $1 $2 >> config.log
-    $CXX conftest.cpp -Werror -o conftest $1 $2 2>> config.log
+    echo $CXX conftest.cpp -o conftest $1 $2 >> config.log
+    $CXX conftest.cpp -o conftest $1 $2 2>> config.log
     ret=$?
     echo $ret >> config.log
     rm -f conftest*
@@ -81,12 +82,9 @@ TARGET_OS=""
 CROSS=""
 
 SYSROOT=""
-CXX="clang++"
-LD="clang++"
+CXX="g++"
+LD="g++"
 STRIP="strip"
-
-test -n "$(which $CXX 2> /dev/null)" || CXX="g++"
-test -n "$(which $LD 2> /dev/null)" || LD="g++"
 
 DEBUG=""
 
@@ -95,7 +93,6 @@ LIBNAME=""
 CXXFLAGS="-std=c++11 -Wall -I. -I$SRCDIR/src"
 LDFLAGS=""
 SOFLAGS="-shared -Wl,-Bsymbolic"
-DEPLIBS=""
 OPTFLAGS="-D__SSE"
 TARGET="-mssse3"
 
@@ -111,10 +108,11 @@ for opt; do
             ;;
         --enable-debug)
             DEBUG="enabled"
-            XCXXFLAGS="$XCXXFLAGS -g"
+            CXXFLAGS="$CXXFLAGS -g"
             ;;
         --cxx=*)
             CXX="$optarg"
+            LD="$optarg"
             ;;
         --extra-cxxflags=*)
             XCXXFLAGS="$optarg"
@@ -143,14 +141,6 @@ for opt; do
             ;;
         --sse)
             OPTFLAGS="-D__SSE"
-            ;;
-        --gcc)
-            CXX="g++"
-            LD="g++"
-            ;;
-        --clang)
-            CXX="clang++"
-            LD="clang++"
             ;;
         --target=*)
             TARGET="-m$optarg"
@@ -183,12 +173,10 @@ case "$TARGET_OS" in
         ;;
     *darwin*)
         LIBNAME="libit.dylib"
-        DEPLIBS="$DEPLIBS vapoursynth"
         SOFLAGS="$SOFLAGS -dynamiclib -Wl,-undefined,suppress -Wl,-read_only_relocs,suppress -Wl,-flat_namespace"
         ;;
     *linux*)
         LIBNAME="libit.so"
-        DEPLIBS="$DEPLIBS vapoursynth"
         CXXFLAGS="$CXXFLAGS -fPIC"
         SOFLAGS="$SOFLAGS -fPIC"
         ;;
@@ -201,29 +189,31 @@ log_echo "CXXFLAGS/LDFLAGS checking..."
 if ! cc_check "$CXXFLAGS" "$LDFLAGS"; then
     error_exit "invalid CXXFLAGS/LDFLAGS"
 fi
-if cc_check "-Os -ffast-math $CXXFLAGS" "$LDFLAGS"; then
-    CXXFLAGS="-Os -ffast-math $CXXFLAGS"
+if cc_check "-O2 -ffast-math $CXXFLAGS" "$LDFLAGS"; then
+    CXXFLAGS="-O2 -ffast-math $CXXFLAGS"
 fi
-if cc_check "$CXXFLAGS -fexcess-precision=fast" "$LDFLAGS"; then
-    CXXFLAGS="$CXXFLAGS -fexcess-precision=fast"
+if cc_check "$CXXFLAGS" "$LDFLAGS"; then
+    CXXFLAGS="$CXXFLAGS"
 fi
 
 PKGCONFIGBIN="pkg-config"
 test -n "$(which ${CROSS}${PKGCONFIGBIN} 2> /dev/null)" && \
     PKGCONFIGBIN=${CROSS}${PKGCONFIGBIN}
 
-if $PKGCONFIGBIN --exists $DEPLIBS 2> /dev/null; then
-    LIBS="$($PKGCONFIGBIN --libs $DEPLIBS)"
-    CXXFLAGS="$CXXFLAGS $($PKGCONFIGBIN --cflags $DEPLIBS)"
+log_echo "checking for vapoursynth headers..."
+if $PKGCONFIGBIN --exists vapoursynth 2> /dev/null; then
+    VSCFLAGS="$($PKGCONFIGBIN --cflags vapoursynth)"
 else
-    for lib in $DEPLIBS; do
-        LIBS="$LIBS -l${lib#lib}"
-    done
-    log_echo "warning: pkg-config or pc files not found, lib detection may be inaccurate."
+    log_echo "warning: pkg-config or pc files not found, header detection may be inaccurate."
+fi
+if ! cc_check "$CXXFLAGS $VSCFLAGS" "$LDFLAGS $LIBS $XLIBS" "VapourSynth.h" "getVapourSynthAPI;" ; then
+    log_echo "error: vapoursynth checking failed."
+    error_exit "VapourSynth.h might not be installed."
 fi
 
 LDFLAGS="$SOFLAGS $LDFLAGS"
 LIBS="$LIBS $XLIBS"
+CXXFLAGS="$CXXFLAGS $VSCFLAGS"
 
 
 cat >> config.mak << EOF
